language: python
script: pytest test_sample.py
env: 
  global:
    - MAIL_PASSWORD=MoonJelly323#@#
    - DATABASE_URL=postgres://postgres@localhost/moon_jelly_test
services:
  - postgresql 
before_script:
  - psql -c 'create database moon_jelly_test;' -U postgres 
